### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [kimyvgy/gitstatus-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by kimyvgy** [comment]
Thank you so much! I will add a license soon.

**Comment by kimyvgy** [comment]
I'd like to close this issue because I have been created a MIT license at the commit bec93711a29c37ef7e63f9e5d805764abe945363. Thank you so much!
